package net.thumbtack.school.buscompany.exception;

public enum ErrorCode {
    FIRSTNAME_INVALID,
    LASTNAME_INVALID,
    PATRONYMIC_INVALID,
    LOGIN_INVALID,
    LOGIN_TOO_LONG,
    LOGIN_TOO_SHORT,
    PASSWORD_TOO_LONG,
    PASSWORD_TOO_SHORT,
    USER_ALREADY_ONLINE,
    USER_IS_OFFLINE,
    INVALID_LOGIN_OR_PASSWORD,
    INVALID_PASSWORD,
    USER_ALREADY_EXISTS,
    USER_NOT_EXISTS,
    UNABLE_TO_OPEN_SESSION,
    UNABLE_TO_CLOSE_SESSION,
    OPERATION_NOT_ALLOWED,
    DUPLICATE_BUS,
    DATABASE_ERROR,
    TRIP_ALREADY_EXISTS,
    DATES_AND_SCHEDULE_INVOLVED,
    TRIP_NOT_EXISTS,
    EMPTY_SCHEDULE,
    EMPTY_DATES_LIST;
}
